version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $IMAGE_TAG
      # Debugging
      # - aws sts get-caller-identity
      # - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 404889086824.dkr.ecr.us-west-2.amazonaws.com
      # - cat ~/.docker/config.json

      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
      # - python -m unittest discover tests

  build:
    commands:
      - pushd entity_formation_string_comparison; ./deploy.sh $IMAGE_TAG; popd
      - pushd entity_formation_model_updated_th; ./deploy.sh $IMAGE_TAG; popd
      - pushd fax_accuracy_model; ./deploy.sh $IMAGE_TAG; popd
      - pushd fax_model_dao; ./deploy.sh $IMAGE_TAG; popd
      - pushd hce_cat_classifier; ./deploy.sh $IMAGE_TAG; popd
      - pushd twilio_carrier_lookup; ./deploy.sh $IMAGE_TAG; popd
      - pushd locations_address_ingestion; ./deploy.sh $IMAGE_TAG; popd
      - pushd hce_confidence; ./deploy.sh $IMAGE_TAG; popd
      - pushd provider_location_confidence; ./deploy.sh $IMAGE_TAG; popd
      # - codebuild-breakpoint
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml --metadata ImageTag=$IMAGE_TAG
      - echo $S3_BUCKET
      - cat template-export.yml
      - cat template-configuration.json

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g;s/\$IMAGE_TAG\$/'${IMAGE_TAG}'/g' template-configuration.json
      # Need this to substitute in the right ECR image tag
      - sed -i.bak s/'${ImageTag}'/$IMAGE_TAG/g template-export.yml
      - cat template-export.yml
      - cat template-configuration.json

artifacts:
  files:
    - template-export.yml
    - template-configuration.json