AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole
    Environment:
      Variables:
        DB_RAPID_USER: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:DB_RAPID_USER}}'
        DB_RAPID_PASSWORD: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:DB_RAPID_PASSWORD}}'
        DB_RAPID_HOST_RW: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:DB_RAPID_HOST_RW}}'
        DB_RAPID_HOST_RO: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:DB_RAPID_HOST_RO}}'
        DB_RAPID_NAME: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:DB_RAPID_NAME}}'
        DB_NORMALIZED_USER: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:DB_NORMALIZED_USER}}'
        DB_NORMALIZED_PASSWORD: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:DB_NORMALIZED_PASSWORD}}'
        DB_NORMALIZED_HOST_RW: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:DB_NORMALIZED_HOST_RW}}'
        DB_NORMALIZED_HOST_RO: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:DB_NORMALIZED_HOST_RO}}'
        DB_NORMALIZED_NAME: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:DB_NORMALIZED_NAME}}'
        GOOGLE_MAPS_KEY: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:GOOGLE_MAPS_KEY}}'
        TWILIO_AUTH_TOKEN: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:TWILIO_AUTH_TOKEN}}'
        TWILIO_ACCT_SID: '{{resolve:secretsmanager:DS_MS_SECRETS:SecretString:TWILIO_ACCT_SID}}'

Resources:
  EntityFormation:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-EntityFormation'
      PackageType: Image
      ImageUri: '404889086824.dkr.ecr.us-west-2.amazonaws.com/datascience/entity_formation_string_comparison_model:${ImageTag}'
      VpcConfig:
        SecurityGroupIds:
          - sg-08594884ff07fbaf4
        SubnetIds:
          - subnet-0cb7fc3f7aeb0017a
          - subnet-0a6b9d79fe0ad65c7
          - subnet-0f2523f5ad3b8bb90
          - subnet-0d0c646c1072914ba
          - subnet-06b9dd1ae0ebc8551
          - subnet-0c7236f56a97e6fea
          - subnet-062cce0d22cc50ede
          - subnet-0f9ca37a92ab1beba
      Timeout: 120
      MemorySize: 2048
      Role: arn:aws:iam::404889086824:role/rh_dev_lambda_role
      # Role:
      #  Fn::GetAtt:
      #  - LambdaExecutionRole
      #  - Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /entity_formation_comparison
            Method: post
            Auth:
              ApiKeyRequired: true

  EntityFormationUpdatedThomas:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-EntityFormationUpdatedThomas'
      PackageType: Image
      ImageUri: '404889086824.dkr.ecr.us-west-2.amazonaws.com/datascience/entity_formation_model_updated_th:${ImageTag}'
      VpcConfig:
        SecurityGroupIds:
          - sg-08594884ff07fbaf4
        SubnetIds:
          - subnet-0cb7fc3f7aeb0017a
          - subnet-0a6b9d79fe0ad65c7
          - subnet-0f2523f5ad3b8bb90
          - subnet-0d0c646c1072914ba
          - subnet-06b9dd1ae0ebc8551
          - subnet-0c7236f56a97e6fea
          - subnet-062cce0d22cc50ede
          - subnet-0f9ca37a92ab1beba
      Timeout: 120
      MemorySize: 2048
      Role: arn:aws:iam::404889086824:role/rh_dev_lambda_role
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /entity_formation_model_updated_th
            Method: post
            Auth:
              ApiKeyRequired: true
 
  EntityCategoryClassifier:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-EntityCategoryClassifier'
      PackageType: Image
      ImageUri: '404889086824.dkr.ecr.us-west-2.amazonaws.com/datascience/entity_category_classifier:${ImageTag}'
      VpcConfig:
        SecurityGroupIds:
          - sg-08594884ff07fbaf4
        SubnetIds:
          - subnet-0cb7fc3f7aeb0017a
          - subnet-0a6b9d79fe0ad65c7
          - subnet-0f2523f5ad3b8bb90
          - subnet-0d0c646c1072914ba
          - subnet-06b9dd1ae0ebc8551
          - subnet-0c7236f56a97e6fea
          - subnet-062cce0d22cc50ede
          - subnet-0f9ca37a92ab1beba
      Timeout: 60
      MemorySize: 2048
      Role: arn:aws:iam::404889086824:role/rh_dev_lambda_role
      # Role:
      #   Fn::GetAtt:
      #   - LambdaExecutionRole
      #   - Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /classify_entity_category
            Method: post
            Auth:
              ApiKeyRequired: true
 
  FaxAccuracyModel:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-FaxAccuracyModel'
      PackageType: Image
      ImageUri: '404889086824.dkr.ecr.us-west-2.amazonaws.com/datascience/fax_accuracy_model:${ImageTag}'
      VpcConfig:
        SecurityGroupIds:
          - sg-08594884ff07fbaf4
        SubnetIds:
          - subnet-0cb7fc3f7aeb0017a
          - subnet-0a6b9d79fe0ad65c7
          - subnet-0f2523f5ad3b8bb90
          - subnet-0d0c646c1072914ba
          - subnet-06b9dd1ae0ebc8551
          - subnet-0c7236f56a97e6fea
          - subnet-062cce0d22cc50ede
          - subnet-0f9ca37a92ab1beba
      Timeout: 60
      MemorySize: 2048
      Role: arn:aws:iam::404889086824:role/rh_dev_lambda_role
      # Role:
      #   Fn::GetAtt:
      #   - LambdaExecutionRole
      #   - Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /fax_accuracy_model
            Method: post
            Auth:
              ApiKeyRequired: true

  FaxModelDAO:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-FaxModelDAO'
      PackageType: Image
      ImageUri: '404889086824.dkr.ecr.us-west-2.amazonaws.com/datascience/fax_model_dao:${ImageTag}'
      VpcConfig:
        SecurityGroupIds:
          - sg-08594884ff07fbaf4
        SubnetIds:
          - subnet-0cb7fc3f7aeb0017a
          - subnet-0a6b9d79fe0ad65c7
          - subnet-0f2523f5ad3b8bb90
          - subnet-0d0c646c1072914ba
          - subnet-06b9dd1ae0ebc8551
          - subnet-0c7236f56a97e6fea
          - subnet-062cce0d22cc50ede
          - subnet-0f9ca37a92ab1beba
      Timeout: 60
      MemorySize: 2048
      Role: arn:aws:iam::404889086824:role/rh_dev_lambda_role
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /fax_model_dao
            Method: post
            Auth:
              ApiKeyRequired: true

  ProviderLinkingModelDAO:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-ProviderLinkingModelDAO'
      PackageType: Image
      ImageUri: '404889086824.dkr.ecr.us-west-2.amazonaws.com/datascience/provider_location_confidence:${ImageTag}'
      VpcConfig:
        SecurityGroupIds:
          - sg-08594884ff07fbaf4
        SubnetIds:
          - subnet-0cb7fc3f7aeb0017a
          - subnet-0a6b9d79fe0ad65c7
          - subnet-0f2523f5ad3b8bb90
          - subnet-0d0c646c1072914ba
          - subnet-06b9dd1ae0ebc8551
          - subnet-0c7236f56a97e6fea
          - subnet-062cce0d22cc50ede
          - subnet-0f9ca37a92ab1beba
      Timeout: 60
      MemorySize: 2048
      Role: arn:aws:iam::404889086824:role/rh_dev_lambda_role
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /provider_linking_model_dao
            Method: post
            Auth:
              ApiKeyRequired: true

  TwilioCarrierLookup:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-TwilioCarrierLookup'
      PackageType: Image
      ImageUri: '404889086824.dkr.ecr.us-west-2.amazonaws.com/datascience/twilio_carrier_lookup:${ImageTag}'
      VpcConfig:
        SecurityGroupIds:
          - sg-08594884ff07fbaf4
        SubnetIds:
          - subnet-0cb7fc3f7aeb0017a
          - subnet-0a6b9d79fe0ad65c7
          - subnet-0f2523f5ad3b8bb90
          - subnet-0d0c646c1072914ba
          - subnet-06b9dd1ae0ebc8551
          - subnet-0c7236f56a97e6fea
          - subnet-062cce0d22cc50ede
          - subnet-0f9ca37a92ab1beba
      Timeout: 60
      MemorySize: 2048
      Role: arn:aws:iam::404889086824:role/rh_dev_lambda_role
      # Role:
      #   Fn::GetAtt:
      #   - LambdaExecutionRole
      #   - Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /twilio_carrier_lookup
            Method: post
            Auth:
              ApiKeyRequired: true

  LocationAddressIngestion:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-LocationAddressIngestion'
      PackageType: Image
      ImageUri: '404889086824.dkr.ecr.us-west-2.amazonaws.com/datascience/locations_address_ingestion:${ImageTag}'
      VpcConfig:
        SecurityGroupIds:
          - sg-08594884ff07fbaf4
        SubnetIds:
          - subnet-0cb7fc3f7aeb0017a
          - subnet-0a6b9d79fe0ad65c7
          - subnet-0f2523f5ad3b8bb90
          - subnet-0d0c646c1072914ba
          - subnet-06b9dd1ae0ebc8551
          - subnet-0c7236f56a97e6fea
          - subnet-062cce0d22cc50ede
          - subnet-0f9ca37a92ab1beba
      Timeout: 60
      MemorySize: 2048
      Role: arn:aws:iam::404889086824:role/rh_dev_lambda_role
      # Role:
      #   Fn::GetAtt:
      #   - LambdaExecutionRole
      #   - Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /location-ingestion
            Method: post
            Auth:
              ApiKeyRequired: true

  HCEConfidence:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-HCEConfidence'
      PackageType: Image
      ImageUri: '404889086824.dkr.ecr.us-west-2.amazonaws.com/datascience/hce_confidence:${ImageTag}'
      VpcConfig:
        SecurityGroupIds:
          - sg-08594884ff07fbaf4
        SubnetIds:
          - subnet-0cb7fc3f7aeb0017a
          - subnet-0a6b9d79fe0ad65c7
          - subnet-0f2523f5ad3b8bb90
          - subnet-0d0c646c1072914ba
          - subnet-06b9dd1ae0ebc8551
          - subnet-0c7236f56a97e6fea
          - subnet-062cce0d22cc50ede
          - subnet-0f9ca37a92ab1beba
      Timeout: 60
      MemorySize: 2048
      Role: arn:aws:iam::404889086824:role/rh_dev_lambda_role
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /score-hce
            Method: post
            Auth:
              ApiKeyRequired: true

  ProviderLocationConfidence:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-ProviderLocationConfidence'
      PackageType: Image
      ImageUri: '404889086824.dkr.ecr.us-west-2.amazonaws.com/datascience/provider_location_confidence:${ImageTag}'
      VpcConfig:
        SecurityGroupIds:
          - sg-08594884ff07fbaf4
        SubnetIds:
          - subnet-0cb7fc3f7aeb0017a
          - subnet-0a6b9d79fe0ad65c7
          - subnet-0f2523f5ad3b8bb90
          - subnet-0d0c646c1072914ba
          - subnet-06b9dd1ae0ebc8551
          - subnet-0c7236f56a97e6fea
          - subnet-062cce0d22cc50ede
          - subnet-0f9ca37a92ab1beba
      Timeout: 60
      MemorySize: 2048
      Role: arn:aws:iam::404889086824:role/rh_dev_lambda_role
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /provider_location_confidence
            Method: post
            Auth:
              ApiKeyRequired: true

  # LambdaExecutionRole:
  #   Description: Creating service role in IAM for AWS Lambda
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: !Sub 'CodeStar-${ProjectId}-Execution${Stage}'
  #     AssumeRolePolicyDocument:
  #       Statement:
  #       - Effect: Allow
  #         Principal:
  #           Service: [lambda.amazonaws.com]
  #         Action: sts:AssumeRole
  #     Path: /
  #     ManagedPolicyArns:
  #       - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
  #     PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary'